#!/bin/sh

#
# MAPPINGS
#

# terminal
riverctl map normal Alt Return spawn foot

# browser
riverctl map normal Alt b spawn firefox
riverctl map normal Alt+Shift p spawn 'firefox --private-window'

# app launcher
riverctl map normal Alt m spawn 'foot sway-launcher-desktop'

# close the focused view
riverctl map normal Alt+Shift q close

# exit river
riverctl map normal Super+Shift e exit

# decrease/increase the main ratio of rivertile
riverctl map normal Alt H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Alt L send-layout-cmd rivertile "main-ratio +0.05"

# increment/decrement the main count of rivertile(1)
riverctl map normal Alt+Shift h send-layout-cmd rivertile "main-count +1"
riverctl map normal Alt+Shift l send-layout-cmd rivertile "main-count -1"

# focus the next/previous view in the layout stack
riverctl map normal Alt j focus-view next
riverctl map normal Alt k focus-view previous

# swap the focused view with the next/previous view in the layout stack
riverctl map normal Alt+Shift j swap next
riverctl map normal Alt+Shift k swap previous

# bump the focused view to the top of the layout stack
riverctl map normal Alt+Shift Return zoom

# fullscreen
riverctl map normal Alt f toggle-fullscreen

# toggle float
riverctl map normal Alt Space toggle-float

# change layout orientation
riverctl map normal Alt Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Alt Right send-layout-cmd rivertile "main-location right"
riverctl map normal Alt Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Alt Left  send-layout-cmd rivertile "main-location left"

# tags
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # focus
    riverctl map normal Alt $i set-focused-tags $tags
    # tag focused view
    riverctl map normal Alt+Shift $i set-view-tags $tags

    # TODO: Understand toggling tags.
    # Alt+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Alt+Control $i toggle-focused-tags $tags
    # Alt+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Alt+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
# focus all tags
riverctl map normal Alt 0 set-focused-tags $all_tags
# tag focused view with all tags
riverctl map normal Alt+Shift 0 set-view-tags $all_tags

# media keys
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'
    riverctl map $mode None XF86AudioMicMute      spawn 'pamixer --default-source --toggle-mute'
    riverctl map $mode None F12                   spawn 'pamixer -i 5'
    riverctl map $mode None F11                   spawn 'pamixer -d 5'
    riverctl map $mode None F10                   spawn 'pamixer --toggle-mute'
    riverctl map $mode None F9                    spawn 'pamixer --default-source --toggle-mute'

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set 5%+'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
    riverctl map $mode None F8                    spawn 'brightnessctl set 5%+'
    riverctl map $mode None F7                    spawn 'brightnessctl set 5%-'
done

#
# INPUT CONFIGURATION
#

#--- touchpad / trackpoint ---

# Use device names that are listed by `riverctl list-inputs` here.
touchpad="1267:47:Elan_Touchpad"
trackpoint="1267:47:Elan_TrackPoint"
# tap to click
riverctl input $touchpad tap enabled
# cursor speed
riverctl input $touchpad pointer-accel 0.4
riverctl input $trackpoint pointer-accel 0.2
# natural scroll
riverctl input $touchpad natural-scroll enabled
riverctl input $trackpoint natural-scroll enabled

# TODO: hide cursor
# It doesn't seem to be released yet, but it has already been implemented.
# https://github.com/riverwm/river/pull/552
# riverctl hide-cursor timeout 5000

#--- keyboard ---
# NOTE: To use CapsLock as Ctrl, set `XKB_DEFAULT_OPTIONS=caps:ctrl_modifier`.

# repeat rate
riverctl set-repeat 50 300

#
# MISC
#

# color
riverctl background-color 0x002b36 # TODO
riverctl border-color-focused 0x68DDC4
riverctl border-color-unfocused 0x586e75

# Japanese IM
fcitx5 &

# Improve startup time of gtk+ apps (including firefox).
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river

# floating window
# Google Meet
riverctl float-filter-add title "Firefox — Sharing Indicator"
# Kanbanflow
riverctl float-filter-add title "^$"

##############################

# TODO: output???

# Alt+Period and Alt+Comma to focus the next/previous output
riverctl map normal Alt Period focus-output next
riverctl map normal Alt Comma focus-output previous

# Alt+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Alt+Shift Period send-to-output next
riverctl map normal Alt+Shift Comma send-to-output previous

##############################

# Super+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt h move left 100
riverctl map normal Super+Alt j move down 100
riverctl map normal Super+Alt k move up 100
riverctl map normal Super+Alt l move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal Super+Alt+Control h snap left
riverctl map normal Super+Alt+Control j snap down
riverctl map normal Super+Alt+Control k snap up
riverctl map normal Super+Alt+Control l snap right

# Super+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Alt + Left Mouse Button to move views
riverctl map-pointer normal Alt BTN_LEFT move-view

# Alt + Right Mouse Button to resize views
riverctl map-pointer normal Alt BTN_RIGHT resize-view

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
exec rivertile -view-padding 0 -outer-padding 0
