theme = "autumn_night"

[editor]
scrolloff = 0
mouse = false
cursorline = true
auto-format = false
auto-pairs = false
true-color = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
";" = "repeat_last_motion"
"'" = "collapse_selection"
# move betweeen windows
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
# buffer operations
C-n = "goto_next_buffer"
C-p = "goto_previous_buffer"
# Vim compatibility
0 = "goto_line_start"

[keys.insert]
j = { j = "normal_mode" }

[keys.select]
"'" = "collapse_selection"
o = "flip_selections"
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
