theme = "ayu_dark"

[editor]
scrolloff = 0
mouse = false
cursorline = true
auto-format = false
auto-pairs = false
true-color = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = false

[editor.soft-wrap]
enable = true

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
";" = "repeat_last_motion"
"'" = "collapse_selection"
# buffer operations
C-j = "goto_next_buffer"
C-k = "goto_previous_buffer"
C-o = "goto_last_accessed_file"

[keys.insert]
j = { j = "normal_mode" }

[keys.select]
"'" = "collapse_selection"
