[[language]]
# Install rust-analyzer first.
# https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers#rust_analyzer
name = "rust"
file-types = ["rs"]
language-server = { command = "rustup", args = ["run", "stable", "rust-analyzer"] }

[[language]]
name = "c"
file-types = ["c", "h"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "typescript"
file-types = ["ts"]
language-server = { command = "typescript-language-server", args = ["--stdio"], language-id = "typescript"}
