bar:
  height: 24
  location: top
  font: Noto Sans:pixelsize=14
  foreground: eeeeeeff
  background: 2E3440dd
  margin: 8
  spacing: 8

  left:
    - river:
        anchors:
          - base: &river_base
              margin: 10
              conditions:
                id == 1: {string: {text: 1}}
                id == 2: {string: {text: 2}}
                id == 3: {string: {text: 3}}
                id == 4: {string: {text: 4}}
                id == 5: {string: {text: 5}}
                id == 6: {string: {text: 6}}
                id == 7: {string: {text: 7}}
                id == 8: {string: {text: 8}}
                id == 9: {string: {text: 9}}
        content:
          map:
            conditions:
              urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: d08770ff}}
              focused || visible:
                map:
                  <<: *river_base
                  deco: {
                    stack: [
                      {background: {color: 81a1c1ff}},
                      {underline: {size: 4, color: d8dee9ff}}
                    ]
                  }
              ~visible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 4, color: ea6962ff}}
              ~visible:
                map:
                  <<: *river_base

  right:
    - pulse:
        content:
          map:
            conditions:
              ~sink_muted && ~source_muted:
                - string: {text: "vol: {sink_percent}%", right-margin: 8}
                - string: {text: "mic: {source_percent}%"}
              ~sink_muted && source_muted:
                - string: {text: "vol: {sink_percent}%", right-margin: 8}
                - string: {text: "mic: {source_percent}% (muted)"}
              sink_muted && ~source_muted:
                - string: {text: "vol: {sink_percent}% (muted)", right-margin: 8}
                - string: {text: "mic: {source_percent}%"}
              sink_muted && source_muted:
                - string: {text: "vol: {sink_percent}% (muted)", right-margin: 8}
                - string: {text: "mic: {source_percent}% (muted)"}
    - battery:
        name: BAT0
        content:
          map:
            default: {string: {text: "bat: {capacity}%"}}
            conditions:
              state == charging: {string: {text: "bat: {capacity}% (charging)", foreground: ffa600ff}}
              capacity <= 20: {string: {text: "bat: {capacity}%", foreground: ff0000ff}}
    - clock:
        date-format: "%Y-%m-%d"
        content:
          - string: {text: "{date}", right-margin: 2}
          - string: {text: "{time}"}
