# PATH
# ref: https://zsh.sourceforge.io/Guide/zshguide02.html#l24
typeset -U path
path=(
  # cargo
  $HOME/.cargo/bin
  # nodenv
  $HOME/.nodenv/bin
  $path
)
export PATH

# Firefox on Wayland
export MOZ_ENABLE_WAYLAND=1

# fcitx5
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# for screen sharing
export XDG_CURRENT_DESKTOP=sway
