# history file
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

# Emacs key bindings
bindkey -e

autoload -Uz compinit promptinit
compinit
promptinit

# autocompletion
zstyle ':completion:*' menu select

# prompt
PROMPT='%B%(?..[%?] )%b%n@%M:%~ $ '

# aliases
alias ls='ls --color=auto'
alias vi='nvim'
alias t='tmux'
alias g='gix'

# Load nodenv
eval "$(nodenv init -)"
